TCP: TCPClient TCPServer

TCPClient: TCPClient.cc
	g++ -o client TCPClient.cc

TCPServer: TCPServer.cc
	g++ -o server TCPServer.cc

UDP: UDPClient UDPServer

UDPClient: UDPClient.cc
	g++ -o client UDPClient.cc

UDPServer: UDPServer.cc
	g++ -o server UDPServer.cc

clean:
	rm client server
