TCP: TCPClient TCPServer

TCPClient: TCPClient.cc
	g++ -o client TCPClient.cc

TCPServer: TCPServer.c
	g++ -o server TCPServer.c

UDP: UDPClient UDPServer

UDPClient: UDPClient.cc
	g++ -o client UDPClient.cc

UDPServer: UDPServer.c
	g++ -o server UDPServer.cc

clean:
	rm client server
